### ISSUE TITLE
no pictures

### ISSUE THREAD

**Issue by wuliwux** [ioBroker/ioBroker.vis-plumb#1]
no pictures in vis
greets

**Comment by GermanBluefox** [comment]
iobroker u vis

10 Июл 2017 г. 1:07 пользователь "wuliwux" <notifications@github.com>
написал:

no pictures in vis
greets

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ioBroker/ioBroker.vis-plumb/issues/1>, or mute the
thread

**Comment by wuliwux** [comment]
can be closed.
this helps:
cd /opt/iobroker
sudo iobroker stop
sudo iobroker upload all
sudo iobroker start

sorry

**Comment by Apollon77** [comment]
Thanks
